spring.application.name=producer-service

spring.kafka.bootstrap-servers=localhost:9092

server.port=8081

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted